export const FETCH_ALL_LISTINGS = "FETCH_ALL_LISTINGS";
export const FETCH_LISTING_BY_ID = "FETCH_LISTING_BY_ID";
export const CREATE_LISTING = "CREATE_LISTING"

export const FETCH_USER_BY_ID = "FETCH_USER_BY_ID";